
package org.konte.ui;

import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.Properties;
import javax.swing.JComboBox;


public class GenerateDialog extends javax.swing.JFrame {
    private Properties props;
    private KeyEventPostProcessor pp = new KeyEventPostProcessor()
    {

        public boolean postProcessKeyEvent(KeyEvent evt)
        {
            if (evt.getKeyCode() == evt.VK_ENTER)
            {
                generate(null);
            } else if (evt.getKeyCode() == evt.VK_ESCAPE)
            {
                hideMe();
            }
            return true;
        }

    };

    /** Creates new form GenerateDialog */
    public GenerateDialog(Properties props)
    {
        initComponents();
        this.props = props;
        String width = props.getProperty("png-width");
        String height = props.getProperty("png-height");
        if (width != null)
            this.widthLabel.setText(width);
        if (height != null)
            this.heightLabel.setText(height);
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventPostProcessor(pp);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        widthLabel = new javax.swing.JTextField();
        heightLabel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        presets = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                formKeyReleased(evt);
            }
        });

        widthLabel.setText("1000");
        widthLabel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                widthLabelActionPerformed(evt);
            }
        });
        widthLabel.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                widthLabelKeyReleased(evt);
            }
        });

        heightLabel.setText("1000");
        heightLabel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                heightLabelActionPerformed(evt);
            }
        });
        heightLabel.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                heightLabelKeyReleased(evt);
            }
        });

        jLabel1.setText("width");

        jLabel2.setText("height");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel3.setText("Generate to size");

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                generate(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        presets.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1000 * 1000", "2000 * 2000", "4000 * 4000", "8000 * 8000", "----------", "800 * 600", "1024 * 768", "1200 * 1000", "1600 * 1200", "----------", "32 * 32", "64 * 64", "128 * 128", "256 * 256", "----------", "1024 * 60", "1024 * 100", "1024 * 200", "----------" }));
        presets.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                presetsActionPerformed(evt);
            }
        });
        presets.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                presetsKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(widthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(heightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(presets, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(widthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(presets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-273)/2, (screenSize.height-239)/2, 273, 239);
    }// </editor-fold>//GEN-END:initComponents

    private void widthLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widthLabelActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_widthLabelActionPerformed

    private void heightLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightLabelActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_heightLabelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        hideMe();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void hideMe()
    {
        this.setVisible(false);
        KeyboardFocusManager.getCurrentKeyboardFocusManager().removeKeyEventPostProcessor(pp);
    }
    
    private void generate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate
        String ss = widthLabel.getText() + " * " + heightLabel.getText();
        boolean found = false;
        for (int i =0; i < presets.getItemCount(); i++)
        {
            String s = (String)presets.getItemAt(i);
            if (s.equals(ss))
                found = true;
        }
        if (! found)
            presets.addItem(ss);
        try {
            int width = Integer.parseInt(this.widthLabel.getText());
            int height = Integer.parseInt(this.heightLabel.getText());
            if (width <= 0 || height <= 0)
                return;
        }
        catch(Exception ex)
        {
            return;
        }
        props.setProperty("png-width", widthLabel.getText());
        props.setProperty("png-height", heightLabel.getText());
        firePropertyChange("GenerateToSize", null, props);
        //Ui.instance.generatePic(width, height,-1,RenderType.IMAGE, null);
        hideMe();
    }//GEN-LAST:event_generate

    private void presetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presetsActionPerformed
        String[] ss = ((String)((JComboBox)evt.getSource()).getSelectedItem()).
                split(" \\* ");
        System.out.println(ss[0]);
        if (ss.length != 2)
            return;
        widthLabel.setText(ss[0]);
        heightLabel.setText(ss[1]);
    }//GEN-LAST:event_presetsActionPerformed

    private void doWith(KeyEvent evt)
    {
        if (evt.getKeyCode() == evt.VK_ENTER)
        {
            generate(null);
        } else if (evt.getKeyCode() == evt.VK_ESCAPE)
        {
            hideMe();
        }
    }
    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        doWith(evt);
    }//GEN-LAST:event_formKeyReleased

    private void widthLabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_widthLabelKeyReleased
        formKeyReleased(evt);
    }//GEN-LAST:event_widthLabelKeyReleased

    private void heightLabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heightLabelKeyReleased
        formKeyReleased(evt);
    }//GEN-LAST:event_heightLabelKeyReleased

    private void presetsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_presetsKeyReleased
        formKeyReleased(evt);
    }//GEN-LAST:event_presetsKeyReleased
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField heightLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox presets;
    private javax.swing.JTextField widthLabel;
    // End of variables declaration//GEN-END:variables
    
}
