
package org.konte.ui;

import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JTextArea;


public class ReplaceDialog extends javax.swing.JFrame {
    private JTextArea target;
    private ReplaceDialog ref = this;

    private KeyEventPostProcessor pp = new KeyEventPostProcessor()
    {

        public boolean postProcessKeyEvent(KeyEvent evt)
        {
            if (evt.getID() == evt.KEY_RELEASED
                    && evt.getKeyCode() == evt.VK_ENTER)
                    {
                if (jButton1.isFocusOwner())
                    jButton1ActionPerformed(null);
                else if (jButton2.isFocusOwner())
                    jButton2ActionPerformed(null);
                else if (replaceAll.isFocusOwner())
                    replaceAllActionPerformed(null);
                else
                    jButton1ActionPerformed(null);
            } else if (evt.getKeyCode() == evt.VK_ESCAPE)
            {
                setVisible(false);
            }
            return true;
        }

    };

    /** Creates new form ReplaceDialog */
    public ReplaceDialog()
    {
        initComponents();
        KeyListener k = new KeyListener()
        {

            public void keyTyped(KeyEvent e)
            {
                if (e.getKeyChar()==e.VK_ESCAPE)
                    ref.setVisible(false);
            }

            public void keyPressed(KeyEvent e)
            {
//                throw new UnsupportedOperationException("Not supported yet.");
            }

            public void keyReleased(KeyEvent e)
            {
//                throw new UnsupportedOperationException("Not supported yet.");
            }
            
        };
        this.findF.addKeyListener(k);
        this.replaceF.addKeyListener(k);
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventPostProcessor(pp);
    }

    @Override
    public void setVisible(boolean b)
    {
        super.setVisible(b);
        if (b)
        {
            this.toFront();
            this.findF.requestFocus();
            KeyboardFocusManager.getCurrentKeyboardFocusManager().removeKeyEventPostProcessor(pp);
            KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventPostProcessor(pp);
        }
        else
        {
            KeyboardFocusManager.getCurrentKeyboardFocusManager().removeKeyEventPostProcessor(pp);
        }
    }

    
    public void setTarget(JTextArea ta)
    {
        this.target = ta;
    }
    
    private int end = 0;
    private int findNext(int pos, boolean replace, String text)
    {
        String orig = target.getText();
        if (this.jCheckBox1.isSelected())
        {
            Pattern p = Pattern.compile(text);
            Matcher m = p.matcher(orig);
            if (m.find(pos))
            {
                int replaceL = replaceF.getText().length();
                if (replace)
                {
                    target.setText(
                            orig.substring(0, m.start()) +
                            replaceF.getText() +
                            orig.substring(m.end())
                        );
                }
                end = m.end();
                return m.start();
            }
            end = 0;
            return -1;
            
        } 
        int pos2 = orig.indexOf(text, pos);
        if (pos2 >= 0)
        {
            if (replace)
            {
                target.setText(
                        orig.substring(0, pos2) +
                        replaceF.getText() +
                        orig.substring(pos2 + text.length())
                    );
                end = pos2 + replaceF.getText().length();
            }
            else
            {
                end = pos2 + text.length();
            }
            return pos2;
        }
        return -1;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        findF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        replaceF = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        replaceAll = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabel1.setText("Find");

        findF.setNextFocusableComponent(replaceF);

        jLabel2.setText("Replace with");

        replaceF.setNextFocusableComponent(jButton1);

        jCheckBox1.setText("Regexp");
        jCheckBox1.setNextFocusableComponent(findF);

        jButton1.setText("Find");
        jButton1.setNextFocusableComponent(jButton2);
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Replace");
        jButton2.setNextFocusableComponent(replaceAll);
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        replaceAll.setText("Replace All");
        replaceAll.setNextFocusableComponent(jButton4);
        replaceAll.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                replaceAllActionPerformed(evt);
            }
        });

        jButton4.setText("Close");
        jButton4.setNextFocusableComponent(jCheckBox1);
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(replaceF, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(findF, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCheckBox1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(replaceAll, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(findF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2)
                    .addComponent(replaceF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(replaceAll))
                .addGap(27, 27, 27)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-435)/2, (screenSize.height-199)/2, 435, 199);
    }// </editor-fold>//GEN-END:initComponents

    private void replaceAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceAllActionPerformed
        target.setCaretPosition(0);
        int cnt = 0;
        String pattern = findF.getText();
        if (pattern.length() == 0)
            return;
        int ind = target.getCaretPosition();
        int count = 0;
        for(;;)
        {
            ind = findNext(ind, true, pattern);
            if (ind >= 0)
            {
                ind = end;
                count++;
            } else
            if (cnt++ > 0)
                break;
        }
        org.konte.generate.Runtime.sysoutln("replaced " + count + " occurences");
        target.setCaretPosition(0);
}//GEN-LAST:event_replaceAllActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ind = findNext(target.getCaretPosition(), false, findF.getText());
        if (ind >= 0)
        {
            target.setCaretPosition(ind);
            target.setSelectionStart(ind);
            target.setSelectionEnd(end == ind ? ind + findF.getText().length()+1 : end);
        }
        else
        {
            target.setCaretPosition(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int ind = findNext(target.getCaretPosition(), true, findF.getText());
        if (ind >= 0)
        {
            target.setCaretPosition(ind);
            target.setSelectionStart(ind);
            target.setSelectionEnd(end);
        }
        else
        {
            target.setCaretPosition(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField findF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton replaceAll;
    private javax.swing.JTextField replaceF;
    // End of variables declaration//GEN-END:variables

    void focus(char c)
    {
        switch(c)
        {
            case 'f': jButton1.requestFocus(); break;
            case 'h': jButton2.requestFocus(); break;
        }
    }
    
}
